# Machine Learning with Python : Linear Regression with multiple Variable

In [13]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_csv("C:\\Users\\AIMS\\Desktop\\Huzaifa\\AIMS_DataSet2023\\homeprices2.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [31]:
# len(df.columns)
for i in range(len(df.columns)):
    print(df.columns[i])

print(df.columns)


area
bedrooms
age
price
Index(['area', 'bedrooms', 'age', 'price'], dtype='object')


In the above data frame , area,bedrooms,and age are called "Independent Variable/ features" and price is dependent Variable.

y =m1x1 +m2x2 + m3x3 +b
where, 
    Price  i =  m1 * area + m2 * bedrooms + m3 * age + b

In [32]:
# we can fill missing data with a value eg: median of all the values of column 
# df['bedrooms'] 
# or 
df.bedrooms

0    3.0
1    4.0
2    NaN
3    3.0
4    5.0
5    6.0
Name: bedrooms, dtype: float64

In [33]:
df.bedrooms.median()

4.0

In [34]:
# filling the misssing value by median in the data.

df.bedrooms = df.bedrooms.fillna(df.bedrooms.median())


In [35]:
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [36]:
df[['area','bedrooms','age']]

area  bedrooms  age
0  2600       3.0   20
1  3000       4.0   15
2  3200       4.0   18
3  3600       3.0   30
4  4000       5.0    8
5  4100       6.0    8

In [37]:
from sklearn import linear_model
reg = linear_model.LinearRegression()


In [38]:
X = df[['area','bedrooms','age']]
y = df.price


reg.fit(X,y)

LinearRegression()

In [39]:
reg.coef_

array([  112.06244194, 23388.88007794, -3231.71790863])

In [40]:
reg.intercept_ # b

221323.00186540425

In [42]:
# Find the home for the flat of 3000 sqft area, 2 bedrooms and 40 yrs old


reg.predict([[3000,3,40]])

C:\Users\AIMS\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([498408.25158031])

In [44]:
print(112.06244194* 3000 + 23388.88007794 * 3 + -3231.71790863 *40 +221323.00186540425)

498408.25157402427


In [46]:
# Find the home for the flat of 2500 sqft area, 4 bedrooms and 5 yrs old

reg.predict([[2500,4,5]])
# or
print(112.06244194* 2500 + 23388.88007794 * 4+ -3231.71790863 *5 +221323.00186540425)

578876.0374840143


C:\Users\AIMS\anaconda3\lib\site-packages\sklearn\base.py:420: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [47]:
#  This will not Give Warning.

X = df[['area','bedrooms','age']].to_numpy()
y = df.price


reg.fit(X,y)

LinearRegression()

In [49]:
reg.predict([[2500,4,5]])

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       4.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

This file Contains hiring statistics for a firm such as experience of candidate , his written and personal Interview score, Based on these 3 factors , Hr will decide the salaray . Given this data , built a machine learning model for HR Department to help decide salaries for future Candidates. Use the model to predict salaries for :
        2 YEARS, EXP , 9 TEST SCORE , 6 INTERVIEW SCORE ==> 53713.86
        12 YEARS, EXP ,10 TEST SCORE , 10 INTERVIEW SCORE ==>93747.79
    

In [112]:
HR_DF = pd.read_csv(r"C:\Users\AIMS\Desktop\Huzaifa\AIMS_DataSet2023\hiring.csv")
HR_DF

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    NaN                           7      72000
7     eleven                    7.0                           8      80000

In [113]:

# HR_DF['test_score(out of 10)'] = HR_DF['test_score(out of 10)'].fillna(HR_DF['test_score(out of 10)'].mean())
import math 
print(math.floor(HR_DF['test_score(out of 10)'].mean()))
HR_DF['test_score(out of 10)'] = HR_DF['test_score(out of 10)'].fillna(math.floor(HR_DF['test_score(out of 10)'].mean()))
# 

7


In [116]:
HR_DF['experience'] = HR_DF['experience'].fillna('Zero')

In [114]:
HR_DF

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0        NaN                    8.0                           9      50000
1        NaN                    8.0                           6      45000
2       five                    6.0                           7      60000
3        two                   10.0                          10      65000
4      seven                    9.0                           6      70000
5      three                    7.0                          10      62000
6        ten                    7.0                           7      72000
7     eleven                    7.0                           8      80000

In [69]:
pip install word2number

  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
  Created wheel for word2number: filename=word2number-1.1-py3-none-any.whl size=5590 sha256=23f28bf03ddaba8d9ae309589be927893a238ff4013b72d11f37ab5003a04bfa
  Stored in directory: c:\users\aims\appdata\local\pip\cache\wheels\29\85\cd\a78aeab138a03ac89a6ed4f8f00665d5ceb7ac0318c837a086
Successfully built word2number
Note: you may need to restart the kernel to use updated packages.


In [70]:
from word2number import w2n

In [117]:
HR_DF['experience'] = HR_DF['experience'].apply(w2n.word_to_num)

In [118]:
HR_DF

experience  test_score(out of 10)  interview_score(out of 10)  salary($)
0           0                    8.0                           9      50000
1           0                    8.0                           6      45000
2           5                    6.0                           7      60000
3           2                   10.0                          10      65000
4           7                    9.0                           6      70000
5           3                    7.0                          10      62000
6          10                    7.0                           7      72000
7          11                    7.0                           8      80000

This file Contains hiring statistics for a firm such as experience of candidate , his written and personal Interview score, Based on these 3 factors , Hr will decide the salaray . Given this data , built a machine learning model for HR Department to help decide salaries for future Candidates. Use the model to predict salaries for :
        2 YEARS, EXP , 9 TEST SCORE , 6 INTERVIEW SCORE ==> 53713.86
        12 YEARS, EXP ,10 TEST SCORE , 10 INTERVIEW SCORE ==>93747.79
    

In [119]:
X = HR_DF[['experience','test_score(out of 10)','interview_score(out of 10)']].to_numpy()
y = HR_DF['salary($)']

reg.fit(X,y)

LinearRegression()

In [120]:
#  2 YEARS, EXP , 9 TEST SCORE , 6 INTERVIEW SCORE ==> 53713.86
a = reg.predict([[2,9,6]])
print(f"The Predicted Salary of 2 YEARS EXP , 9 TEST SCORE and 6 INTERVIEW SCORE is : {a[0]}")

The Predicted Salary of 2 YEARS EXP , 9 TEST SCORE and 6 INTERVIEW SCORE is : 53713.86677124004


In [121]:
        # 12 YEARS, EXP ,10 TEST SCORE , 10 INTERVIEW SCORE ==>93747.79
a = reg.predict([[12,10,10]])
print(f"The Predicted Salary of 12 YEARS EXP , 10 TEST SCORE and 10 INTERVIEW SCORE is : {a[0]}")

The Predicted Salary of 12 YEARS EXP , 10 TEST SCORE and 10 INTERVIEW SCORE is : 93747.79628650835


Pickling 

In [123]:
#  Saving and Loading Trained Data using python
import pickle

In [124]:
#  Saving the Model using pickle 
with open("C:\\Users\\AIMS\\Desktop\\Huzaifa\\AIMS_DataSet2023\\Model_Pickle",'wb') as f:
   pickle.dump(reg,f)

In [128]:
#  Loading the Model using pickle 

with open("C:\\Users\\AIMS\\Desktop\\Huzaifa\\AIMS_DataSet2023\\Model_Pickle",'rb') as f:
   mp = pickle.load(f)
   print(mp)


LinearRegression()


In [129]:
mp.coef_

array([2922.26901502, 2221.30909959, 2147.48256637])

In [130]:
mp.intercept_

14992.651446693118

In [133]:
mp.predict([[2,9,6]])

array([53713.86677124])